default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: maxwell
  password: post1234
  host: localhost
development:
  <<: *default
  database: hello_rails_development
test:
  <<: *default
  database: hello_rails_test
production:
  <<: *default
  database: hello_rails_production
  username: hello_rails
  password: <%= ENV["HELLO_RAILS_DATABASE_PASSWORD"] %>
